config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tracks.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracks/', include('tracks.urls')),
    path('videos/', include('videos.urls')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracks/urls.py
from django.urls import path
from . import  views


app_name = 'tracks'

urlpatterns = [
    path('list/', views.track_list, name='list'),
    path('create/', views.track_create, name='create'),
    path('detail/<int:pk>/', views.track_detail, name='detail'),
    path('update/<int:pk>/', views.track_update, name='update'),
    path('delete/<int:pk>/', views.track_delete, name='delete'),
]

videos/urls.py
from django.urls import path
from . import  views


app_name = 'videos'

urlpatterns = [
    path('list/', views.video_list, name='list'),
    path('create/', views.video_create, name='create'),
    path('detail/<int:pk>/', views.video_detail, name='detail'),
    path('update/<int:pk>/', views.video_update, name='update'),
    path('delete/<int:pk>/', views.video_delete, name='delete'),
]

tracks/models.py
from django.db import models
from django.shortcuts import reverse


class Track(models.Model):
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    album = models.CharField(max_length=255)
    genre = models.CharField(max_length=100)
    release_date = models.DateField()
    cover_image = models.ImageField(upload_to='cover_images/')
    audio_file = models.FileField(upload_to='audio_files/')

    def get_detail_url(self):
        return reverse('tracks:detail', args=[self.pk])

    def get_update_url(self):
        return reverse('tracks:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('tracks:delete', args=[self.pk])

videos/models.py
from django.db import models
from django.shortcuts import reverse

class Video(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    upload_date = models.DateField()
    video_file = models.FileField(upload_to='videos/')

    def __str__(self):
        return self.title

    def get_detail_url(self):
        return reverse('videos:detail', args=[self.pk])

    def get_update_url(self):
        return reverse('videos:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('videos:delete', args=[self.pk])

tracks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Track


def home(request):
    return render(request, 'index.html')

def track_list(request):
    tracks = Track.objects.all()
    ctx = {'tracks': tracks}
    return render(request, 'tracks/music-list.html', ctx)

def track_create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        artist = request.POST.get('artist')
        album = request.POST.get('album')
        genre = request.POST.get('genre')
        release_date = request.POST.get('release_date')
        cover_image = request.FILES.get('cover_image')
        audio_file = request.FILES.get('audio_file')
        if title and artist and album and genre and cover_image and audio_file:
            Track.objects.create(
                title=title,
                artist=artist,
                album=album,
                genre=genre,
                release_date=release_date,
                cover_image=cover_image,
                audio_file=audio_file
            )
            return redirect('tracks:list')
    return render(request, 'tracks/music-create.html')

def track_update(request, pk):
    track = get_object_or_404(Track, pk=pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        artist = request.POST.get('artist')
        album = request.POST.get('album')
        genre = request.POST.get('genre')
        release_date = request.POST.get('release_date')
        cover_image = request.FILES.get('cover_image')
        audio_file = request.FILES.get('audio_file')
        if title and artist and album and genre and cover_image and audio_file:
            track.title = title
            track.artist = artist
            track.album = album
            track.genre = genre
            track.release_date = release_date
            track.cover_image = cover_image
            track.audio_file = audio_file
            track.save()
            return redirect(track.get_detail_url())
    ctx = {'track': track}
    return render(request, 'tracks/music-create.html', ctx)

def track_detail(request, pk):
    track = get_object_or_404(Track, pk=pk)
    ctx = {'track': track}
    return render(request, 'tracks/music-detail.html', ctx)


def track_delete(request, pk):
    track = get_object_or_404(Track, pk=pk)
    if request.method == "POST":
        track.delete()
        return redirect('tracks:list')
    ctx = {'track': track}
    return render(request, 'tracks/music-delete-confirm.html', ctx)

videos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Video

def video_list(request):
    videos = Video.objects.all()
    ctx = {'videos': videos}
    return render(request, 'videos/video-list.html', ctx)

def video_create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        upload_date = request.POST.get('upload_date')
        video_file = request.FILES.get('video_file')
        if title and description and upload_date and video_file:
            Video.objects.create(
                title=title,
                description=description,
                upload_date=upload_date,
                video_file=video_file,
            )
            return redirect('videos:list')
    return render(request, 'videos/video-create.html')

def video_update(request, pk):
    video = get_object_or_404(Video, pk=pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        upload_date = request.POST.get('upload_date')
        video_file = request.FILES.get('video_file')
        if title and description and upload_date and video_file:
            video.title = title
            video.description = description
            video.upload_date = upload_date
            video.video_file = video_file
            video.save()
            return redirect(video.get_detail_url())
    ctx = {'video': video}
    return render(request, 'videos/video-create.html', ctx)


def video_detail(request, pk):
    video = get_object_or_404(Video, pk=pk)
    ctx = {'video': video}
    return render(request, 'videos/video-detail.html', ctx)

def video_delete(request, pk):
    video = get_object_or_404(Video, pk=pk)
    if request.method == "POST":
        video.delete()
        return redirect('videos:list')
    ctx = {'video': video}
    return render(request, 'videos/video-delete-confirm.html', ctx)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}MusicVideo Hub - Your Entertainment Portal {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">\
</head>
<body>
    <header class="glass-effect">
       {# NAV #}
       {% include 'includes/nav.html' %}
    </header>

    <main>
        {% block content %} {% endblock %}
    </main>

        {# FOOTER #}
        {% include 'includes/footer.html' %}

    <script src="script.js"></script>
</body>
</html>

templates/includes/footer.html
<footer class="glass-effect">
    <p>&copy; 2023 MusicVideo<span>Hub</span>. All rights reserved.</p>
    <div class="social-icons">
        <a href="https://www.facebook.com/people/Samandar-Nayimjonov/pfbid0LLBYn1cMufU4LvYX31EciGPyShyCXDri7KdQqkubxw8Q99Nrt2gZW8uokw5JPLbRl/?mibextid=ZbWKwL"><i class="fab fa-facebook"></i></a>
        <a href="https://www.linkedin.com/in/samandar-nayimjonov-594407329/"><i class="fab fa-linkedin"></i></a>
        <a href="https://instagram.com/1samandar_old"><i class="fab fa-instagram"></i></a>
    </div>
</footer>

templates/includes/nav.html
<nav>
    <div class="logo">
        <a href="{% url 'home' %}">MusicVideo<span>Hub</span></a>
    </div>
    <ul>
        <li><a href="{% url 'home' %}"><i class="fas fa-home"></i> Home</a></li>
        <li><a href="{% url 'tracks:list' %}"><i class="fas fa-music"></i> Music</a></li>
        <li><a href="{% url 'videos:list' %}"><i class="fas fa-video"></i> Videos</a></li>
    </ul>
</nav>

templates/index.html
{% extends 'base.html' %}


{% block title %} MusicVideo Hub - Your Entertainment Portal {% endblock %}

{% block content %}
    <section class="hero">
        <h1 class="animated-text">Welcome to MusicVideo<span>Hub</span></h1>
        <p class="subtitle">Your ultimate destination for music and videos</p>
    </section>

    <section class="featured">
           <div class="featured-item music-card">
                <div class="card-content">
                    <h2>Featured Music</h2>
                    <img src="static\images\ab67616d00001e027b981c68e92698f8b7caf715.jpg" alt="Featured Music">
                    <p>Discover our latest and greatest tracks</p>
                    <a href="{% url 'tracks:list' %}" class="btn pulse">Explore Music</a>
                </div>
           </div>
            <div class="featured-item video-card">
                <div class="card-content">
                    <h2>Featured Video</h2>
                    <img src="static\images\video-300x300.png" alt="Featured Video">
                    <p>Watch our top-rated videos</p>
                    <a href="{% url 'videos:list' %}" class="btn pulse">Explore Videos</a>
                </div>
            </div>
    </section>
{% endblock %}

templates/tracks/music-create.html
{% extends 'base.html' %}


{% block title %} {% if track %} Update Music - MusicVideoHub {% else %} Create Music - MusicVideoHub {% endif %} {% endblock %}

{% block content %}
    <section class="page-header">
        <h1 class="animated-text">{% if track %} Update Music {% else %} Create New Music {% endif %}</h1>
        <a href="{% url 'tracks:list' %}" class="btn"><i class="fas fa-arrow-left"></i> Back to List</a>
    </section>

    <section class="music-form glass-effect">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" id="title" name="title" value="{{ track.title }}" required>
            </div>

            <div class="form-group">
                <label for="artist">Artist</label>
                <input type="text" id="artist" name="artist" value="{{ track.artist }}" required>
            </div>

            <div class="form-group">
                <label for="album">Album</label>
                <input type="text" id="album" name="album" value="{{ track.album }}" >
            </div>

            <div class="form-group">
                <label for="genre">Genre</label>
                <input type="text" id="genre" name="genre" value="{{ track.genre }}" >
            </div>

            <div class="form-group">
                <label for="release_date">Release Date</label>
                {% if track.release_date %}
                <input type="date" id="release_date" name="release_date" value="{{ track.release_date|date:'Y-m-d' }}">
                {% else %}
                <input type="date" id="release_date" name="release_date">
                {% endif %}
            </div>


            <div class="form-group">
                 <label for="cover_image">Cover Image</label>
                {% if track.cover_image %}
                <img src="{{ track.cover_image.url }}" alt="{{ track.title }}" class="current-image" style="width: 350px; height: 200px;">
                {% endif %}
                <input type="file" id="cover_image" name="cover_image" accept="image/*">
            </div>

            <div class="form-group">
                <label for="audio_file">Audio File</label>
                {% if track.audio_file %}
                <audio controls>
                <source src="{{ track.audio_file.url }}" type="audio/mpeg">
                Your browser does not support the audio element.
                </audio>
                {% endif %}
                <br>
                <input type="file" id="audio_file" name="audio_file" accept="audio/*" required>
            </div>

            {% if track %}
            <button type="submit" class="btn btn-primary">Update</button>
            {% else %}
            <button type="submit" class="btn btn-primary">Create New Music</button>
            {% endif %}
        </form>
    </section>
{% endblock %}

templates/tracks/music-delete-confirm.html
{% extends 'base.html' %}


{% block title %} Delete Music Confirmation - MusicVideoHub {% endblock %}

{% block content %}
    <section class="page-header">
        <h1 class="animated-text">Delete Music Confirmation</h1>
        <a href="{% url 'tracks:list' %}" class="btn"><i class="fas fa-arrow-left"></i> Back to List</a>
    </section>

    <section class="delete-confirm glass-effect">
        <h2>Are you sure you want to delete this music?</h2>
        <div class="music-info">
                <img src="{{ track.cover_image.url }}" alt="{{ track.title }}" class="album-cover">
            <div class="music-details">
                <h3>{{ track.title }}</h3>
                <p>{{ track.artist }}</p>
                <p>Album: {{ track.album }}</p>
            </div>
        </div>
            <p class="warning">This action cannot be undone.</p>
        <div class="action-buttons">
            <a href="{% url 'tracks:list' %}" class="btn btn-secondary">Cancel</a>
            <form  method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    </section>
{% endblock %}

templates/tracks/music-detail.html
{% extends 'base.html' %}


{% block title %} Music Detail - MusicVideoHub {% endblock %}

{% block content %}
    <section class="page-header">
        <h1 class="animated-text">Music Detail</h1>
        <a href="{% url 'tracks:list' %}" class="btn"><i class="fas fa-arrow-left"></i> Back to List</a>
    </section>

    <section class="music-detail glass-effect">
        <div class="music-cover">
            <img src="{{ track.cover_image.url }}" alt="{{ track.title }}">
        </div>
        <div class="music-info">
            <h2>{{ track.title }}</h2>
            <p class="artist">{{ track.artist }}</p>
            <p class="album">Album: {{ track.album }}</p>
            <p class="genre">Genre: {{ track.genre }}</p>
            <p class="release-date">Released: {{ track.release_date | date:"Y-m-d" }}</p>
            <div class="music-player">
                <audio controls>
                    <source src="{{ track.audio_file.url }}" type="audio/mpeg">
                    Your browser does not support the audio element.
                </audio>
            </div>
            <div class="action-buttons">
                <a href="{{ track.get_update_url }}" class="btn btn-edit"><i class="fas fa-edit"></i> Edit</a>
                <a href="{{ track.get_delete_url }}" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a>
            </div>
        </div>
    </section>
{% endblock %}

templates/tracks/music-list.html
{% extends 'base.html' %}

{% block title %} Music List - MusicVideoHub {% endblock %}

{% block content %}
    <section class="page-header">
        <h1 class="animated-text">Music Collection</h1>
        <a href="{% url 'tracks:create' %}" class="btn pulse"><i class="fas fa-plus"></i> Add New Music</a>
    </section>

    <section class="music-list">
        {% for track in tracks %}
            <div class="music-item glass-effect">
                <img src="{{ track.cover_image.url }}" alt="{{ track.title }}">
                <div class="music-info">
                    <h3>{{ track.title }}</h3>
                    <p>{{ track.artist }}</p>
                </div>
                <div class="music-actions">
                    <a href="{{ track.get_detail_url }}" class="btn btn-info"><i class="fas fa-info-circle"></i></a>
                    <a href="{{ track.get_update_url }}" class="btn btn-edit"><i class="fas fa-edit"></i></a>
                    <a href="{{ track.get_delete_url }}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                </div>
            </div>
        {% empty %}
            <h3>No music found.</h3>
        {% endfor %}
    </section>
{% endblock %}

templates/videos/video-create.html
{% extends 'base.html' %}


{% block title %} {% if video %} Update Video - MusicVideoHub {% else %} Create Video - MusicVideoHub {% endif %} {% endblock %}

{% block content %}
    <section class="page-header">
        <h1 class="animated-text">{% if video %} Update Video {% else %} Create New Video {% endif %}</h1>
        <a href="{% url 'videos:list' %}" class="btn"><i class="fas fa-arrow-left"></i> Back to List</a>
    </section>

    <section class="music-form glass-effect">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" id="title" name="title" value="{{ video.title }}" required>
            </div>

            <div class="form-group">
                <label for="description">Description</label>
                <textarea id="description" name="description" required>{{ video.description }}</textarea>
            </div>

            <div class="form-group">
                <label for="upload_date">Upload Date</label>
                {% if video.video_file %}
                <input type="date" id="upload_date" name="upload_date" value="{{ video.upload_date|date:'Y-m-d' }}">
                {% else %}
                <input type="date" id="upload_date" name="upload_date">
                {% endif %}
            </div>


            <div class="form-group">
                <label for="video_file">Video File</label>
                {% if video.video_file %}

                    <video controls width="350" height="290">
                        <source src="{{ video.video_file.url }}" type="video/mp4">
                    </video>
                <input type="file" id="video_file" name="video_file">
                {% else %}
                    <input type="file" id="video_file" name="video_file" required>
                {% endif %}
            </div>

            {% if video %}
            <button type="submit" class="btn btn-primary">Update</button>
            {% else %}
            <button type="submit" class="btn btn-primary">Create New Music</button>
            {% endif %}
        </form>
    </section>
{% endblock %}

templates/videos/video-delete-confirm.html
{% extends 'base.html' %}


{% block title %} Delete Video Confirmation - MusicVideoHub {% endblock %}

{% block content %}
    <section class="page-header">
        <h1 class="animated-text">Delete Video Confirmation</h1>
        <a href="{% url 'videos:list' %}" class="btn"><i class="fas fa-arrow-left"></i> Back to List</a>
    </section>

    <section class="delete-confirm glass-effect">
        <h2>Are you sure you want to delete this video?</h2>
        <div class="music-info">
                 <video controls width="350" height="290">
                    <source src="{{ video.video_file.url }}" type="video/mp4">
                </video>
            <div class="music-details">

                <h3>{{ video.title }}</h3>
                <p>Description: {{ video.description }}</p>
            </div>
        </div>
            <p class="warning">This action cannot be undone.</p>
        <div class="action-buttons">
            <a href="{% url 'videos:list' %}" class="btn btn-secondary">Cancel</a>
            <form  method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    </section>
{% endblock %}

templates/videos/video-detail.html
{% extends 'base.html' %}


{% block title %} Video Detail - MusicVideoHub {% endblock %}

{% block content %}
    <section class="page-header">
        <h1 class="animated-text">Music Detail</h1>
        <a href="{% url 'videos:list' %}" class="btn"><i class="fas fa-arrow-left"></i> Back to List</a>
    </section>

    <section class="music-detail glass-effect">
        <video controls width="350" height="290">
            <source src="{{ video.video_file.url }}" type="video/mp4">
        </video>
        <div class="music-info">
            <h2>{{ video.title }}</h2>
            <p> Description: {{ video.description }}</p>
            <p class="release-date">Upload Date: {{ video.upload_date | date:"Y-m-d" }}</p>

            <div class="action-buttons">
                <a href="{{ video.get_update_url }}" class="btn btn-edit"><i class="fas fa-edit"></i> Edit</a>
                <a href="{{ video.get_delete_url }}" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a>
            </div>
        </div>
    </section>
{% endblock %}

templates/videos/video-list.html
{% extends 'base.html' %}

{% block title %} Video List - MusicVideoHub {% endblock %}

{% block content %}
    <section class="page-header">
        <h1 class="animated-text"> Video Collection </h1>
        <a href="{% url 'videos:create' %}" class="btn pulse"><i class="fas fa-plus"></i> Add New Video</a>
    </section>

    <section class="music-list">
        {% for video in videos %}
            <div class="music-item glass-effect">
                <video controls width="350" height="290">
                    <source src="{{ video.video_file.url }}" type="video/mp4">
                </video>

                <div class="music-info">
                    <h3>{{ video.title }}</h3>
                    <p>{{ video.artist }}</p>
                </div>
                <div class="music-actions">
                    <a href="{{ video.get_detail_url }}" class="btn btn-info"><i class="fas fa-info-circle"></i></a>
                    <a href="{{ video.get_update_url }}" class="btn btn-edit"><i class="fas fa-edit"></i></a>
                    <a href="{{ video.get_delete_url }}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                </div>
            </div>
        {% empty %}
            <h3>No video found.</h3>
        {% endfor %}
    </section>
{% endblock %}